name: Continuous Integration

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and test code
        run: docker build

      # - name: Build and push Docker images
      #   uses: docker/build-push-action@v1.1.1
